name: Deploy App
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    outputs: 
      script-file: ${{ steps.publish.outputs.script-file }}

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3 
        with:
          node-version: 18  
      - name: Install dependencies
        run: npm ci 
      - name: Run test
        run:  npm test
      - name: Publish filename
        id: publish
        run:  find dist/asset/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          # path: dist
          path: |
            dist
            package.json
    deploy:
      needs: test
      # needs: [job1, job2 job3]
      runs-on: ubuntu-latest
      steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3 
        with:
          node-version: 18  
      - name: Install dependencies
        run: npm ci 
      - name: Build project
        run: npm run build
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output filename:
        run: echo "${{ needs.test.outputs.script-file }}"  
      - name: Deploy app
        run: echo "deploying....."